CREATE TABLE IF NOT EXISTS posts (
    userId INT NOT NULL,
    id INT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
    postId INT NOT NULL,
    id INT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    email VARCHAR(50) NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (postId) REFERENCES posts(id) ON DELETE CASCADE
);